# Generated by Django 4.2.30 on 2026-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerequipment',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
