# Generated by Django 4.2.30 on 2026-06-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed (Fee Paid)'), ('STARTED', 'Job Started'), ('COMPLETED', 'Job Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=15)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_farmer', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'PROVIDER'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_provider', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='marketplace.quote')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='marketplace.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bookings.booking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_raised', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booking', 'reviewer')},
            },
        ),
    ]
