# Generated by Django 4.2.30 on 2026-07-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_equipment_booking_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_address_type',
            field=models.CharField(default='PROFILE', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
