# Generated by Django 4.2.30 on 2026-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='provider_docs/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
